/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FishIdentificationRouteImport } from './routes/fish-identification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarineAiRouteImport } from './routes/marine-ai'
import { Route as OceanDashboardRouteImport } from './routes/ocean-dashboard'
import { Route as PopulationTrendsRouteImport } from './routes/population-trends'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SpeciesCompareRouteImport } from './routes/species-compare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FishIdentificationRoute = FishIdentificationRouteImport.update({
  id: '/fish-identification',
  path: '/fish-identification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarineAiRoute = MarineAiRouteImport.update({
  id: '/marine-ai',
  path: '/marine-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanDashboardRoute = OceanDashboardRouteImport.update({
  id: '/ocean-dashboard',
  path: '/ocean-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationTrendsRoute = PopulationTrendsRouteImport.update({
  id: '/population-trends',
  path: '/population-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesCompareRoute = SpeciesCompareRouteImport.update({
  id: '/species-compare',
  path: '/species-compare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/fish-identification': typeof FishIdentificationRoute
  '/login': typeof LoginRoute
  '/marine-ai': typeof MarineAiRoute
  '/ocean-dashboard': typeof OceanDashboardRoute
  '/population-trends': typeof PopulationTrendsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/species-compare': typeof SpeciesCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/fish-identification': typeof FishIdentificationRoute
  '/login': typeof LoginRoute
  '/marine-ai': typeof MarineAiRoute
  '/ocean-dashboard': typeof OceanDashboardRoute
  '/population-trends': typeof PopulationTrendsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/species-compare': typeof SpeciesCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/fish-identification': typeof FishIdentificationRoute
  '/login': typeof LoginRoute
  '/marine-ai': typeof MarineAiRoute
  '/ocean-dashboard': typeof OceanDashboardRoute
  '/population-trends': typeof PopulationTrendsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/species-compare': typeof SpeciesCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/fish-identification'
    | '/login'
    | '/marine-ai'
    | '/ocean-dashboard'
    | '/population-trends'
    | '/profile'
    | '/register'
    | '/research'
    | '/species-compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/fish-identification'
    | '/login'
    | '/marine-ai'
    | '/ocean-dashboard'
    | '/population-trends'
    | '/profile'
    | '/register'
    | '/research'
    | '/species-compare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/fish-identification'
    | '/login'
    | '/marine-ai'
    | '/ocean-dashboard'
    | '/population-trends'
    | '/profile'
    | '/register'
    | '/research'
    | '/species-compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  FishIdentificationRoute: typeof FishIdentificationRoute
  LoginRoute: typeof LoginRoute
  MarineAiRoute: typeof MarineAiRoute
  OceanDashboardRoute: typeof OceanDashboardRoute
  PopulationTrendsRoute: typeof PopulationTrendsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResearchRoute: typeof ResearchRoute
  SpeciesCompareRoute: typeof SpeciesCompareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish-identification': {
      id: '/fish-identification'
      path: '/fish-identification'
      fullPath: '/fish-identification'
      preLoaderRoute: typeof FishIdentificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marine-ai': {
      id: '/marine-ai'
      path: '/marine-ai'
      fullPath: '/marine-ai'
      preLoaderRoute: typeof MarineAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean-dashboard': {
      id: '/ocean-dashboard'
      path: '/ocean-dashboard'
      fullPath: '/ocean-dashboard'
      preLoaderRoute: typeof OceanDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population-trends': {
      id: '/population-trends'
      path: '/population-trends'
      fullPath: '/population-trends'
      preLoaderRoute: typeof PopulationTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species-compare': {
      id: '/species-compare'
      path: '/species-compare'
      fullPath: '/species-compare'
      preLoaderRoute: typeof SpeciesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  FishIdentificationRoute: FishIdentificationRoute,
  LoginRoute: LoginRoute,
  MarineAiRoute: MarineAiRoute,
  OceanDashboardRoute: OceanDashboardRoute,
  PopulationTrendsRoute: PopulationTrendsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResearchRoute: ResearchRoute,
  SpeciesCompareRoute: SpeciesCompareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
